import Link from "next/link";

export const metadata = { title: "Services", description: "Industrial hygiene, exposure assessment, noise, ventilation, OSHA compliance, respiratory protection, training, and medical-surveillance support." };

const services = [
  {n:"01",title:"Industrial Hygiene & Exposure Assessment",intro:"Understand what employees are exposed to, how much, and what controls will make the greatest difference.",items:["Personal and area air sampling","Chemical and particulate exposure assessments","Lead, silica, welding fume, solvents and isocyanates","Exposure-control recommendations and technical reports"]},
  {n:"02",title:"Noise & Hearing Conservation",intro:"Move beyond a spot sound-level reading to a defensible picture of employee noise exposure.",items:["Full-shift noise dosimetry","Equipment and process sound-level surveys","Facility noise mapping","Hearing-conservation program evaluation"]},
  {n:"03",title:"Ventilation & Engineering Controls",intro:"Evaluate whether local exhaust and process controls capture contaminants where they are generated.",items:["Local exhaust ventilation assessments","Smoke visualization and airflow studies","Fume hood and capture-system reviews","Control selection and verification sampling"]},
  {n:"04",title:"Safety & OSHA Compliance",intro:"Translate regulatory requirements into programs and practices that fit the way your operation actually works.",items:["Compliance and gap assessments","Written safety programs and procedures","Job hazard analyses and risk assessments","Incident investigation and corrective-action support"]},
  {n:"05",title:"Respiratory Protection",intro:"Build a complete, defensible respiratory-protection program around the hazards and respirators at your facility.",items:["Program development and annual review","Hazard evaluation and respirator selection","Fit-testing program support","Cartridge-change schedule development"]},
  {n:"06",title:"Medical Surveillance & Occupational Health",intro:"RN-led support connects exposure information, biological monitoring, and occupational-health follow-through.",items:["Medical-surveillance program coordination","Biological-monitoring documentation and trending","Employee notification and follow-up processes","Coordination with occupational-health providers"]},
  {n:"07",title:"Training & Program Development",intro:"Give employees and supervisors training that reflects their equipment, materials, tasks, and responsibilities.",items:["Hazard-specific employee training","Supervisor and competent-person training","Customized written programs","Practical forms, permits and field tools"]},
  {n:"08",title:"Confined Space, LOTO & High-Hazard Work",intro:"Strengthen the planning and controls used for complex maintenance, contractor, and non-routine work.",items:["Permit-required confined-space evaluations","Lockout/tagout procedure development","Hot work and fall-protection reviews","Contractor safety and permitting systems"]},
];

export default function ServicesPage(){return <main><section className="page-hero industrial-hero"><div className="shell"><p className="eyebrow">Services</p><h1>From exposure data to practical control.</h1><p>Industrial hygiene, safety, and medical-surveillance support tailored to your operation.</p></div></section><section className="section shell"><div className="section-intro"><p className="eyebrow dark">Full-service support</p><h2>Clear answers for complex workplace hazards.</h2><p className="lead">From focused assessments to ongoing program support, each engagement is built around the decisions you need to make.</p></div><div className="detail-grid">{services.map(s=><article className="detail-card" key={s.title}><span>{s.n}</span><h3>{s.title}</h3><p>{s.intro}</p><ul>{s.items.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div><div className="center-action"><Link className="text-link" href="/medical-surveillance">Explore medical-surveillance services →</Link></div></section><section className="cta"><div className="shell cta-inner"><div><p className="eyebrow">Not sure where to begin?</p><h2>Start with the hazard or compliance question.</h2></div><Link className="button button-light" href="/contact">Discuss Your Project</Link></div></section></main>}
