import Link from "next/link";
import Image from "next/image";

export const metadata = { title: "About", description: "Meet Thomas J. Allen, CIH, CSP, and Bailey Allen, RN—the industrial hygiene, safety, and medical-surveillance team behind Wasatch." };

export default function AboutPage() {
  return <main>
    <section className="page-hero"><div className="shell"><p className="eyebrow">About Wasatch</p><h1>Expert guidance. Practical judgment.</h1><p>Independent industrial hygiene and safety consulting for organizations across the Western United States.</p></div></section>
    <section className="section shell"><div className="about-intro"><Image src="/wasatch-logo.png" alt="Wasatch Industrial Hygiene and Safety, LLC" width={800} height={384} /><div><p className="lead">Wasatch was founded to give employers direct access to experienced, credentialed support without the layers of a large consulting firm.</p><p>Our advantage is coordination: workplace exposure and safety expertise connected directly with occupational-health and medical-surveillance support.</p></div></div><div className="team-grid"><article><p className="eyebrow dark">Founder & Principal Consultant</p><h2>Thomas J. Allen, CIH, CSP</h2><p className="role">Certified Industrial Hygienist • Certified Safety Professional</p><p>Thomas leads exposure assessment, industrial hygiene, occupational safety, OSHA compliance, and control strategy. His approach is grounded in manufacturing and operational environments where recommendations must be defensible, understandable, and practical to implement.</p><ul><li>Exposure assessment and air monitoring</li><li>Noise, ventilation, and respiratory protection</li><li>Safety programs and high-hazard work</li><li>Technical reports and corrective-action strategy</li></ul></article><article><p className="eyebrow dark">Medical Surveillance & Occupational Health</p><h2>Bailey Allen, RN</h2><p className="role">Registered Nurse • Medical-Surveillance Specialist</p><p>Bailey leads medical-surveillance and biological-monitoring support, helping connect workplace exposure information with employee follow-up and occupational-health coordination.</p><ul><li>Medical-surveillance program support</li><li>Biological-monitoring documentation and trending</li><li>Exposure-history and work-activity review</li><li>Coordination with occupational-health providers</li></ul><Link href="/medical-surveillance" className="text-link">Explore medical-surveillance support →</Link></article></div><div className="values-row values-centered"><span>Independent judgment</span><span>Clear communication</span><span>Practical control</span><span>Coordinated follow-through</span></div></section>
  </main>;
}
