import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Frequently Asked Questions", description: "Answers about industrial hygiene consulting, exposure monitoring, service areas, project timing, and medical surveillance support." };
const faqs=[
  ["When should we contact an industrial hygienist?","When introducing a new process or chemical, investigating an employee concern, evaluating an exposure, responding to a regulatory issue, selecting controls, or validating that existing controls are effective."],
  ["Can you perform workplace exposure monitoring?","Yes. Wasatch can help develop a sampling strategy and conduct personal or area monitoring for airborne contaminants and noise, followed by interpretation and a clear technical report."],
  ["Do you support short-term projects?","Yes. Engagements can range from a focused assessment or single sampling event to ongoing compliance and program support."],
  ["Can you help us determine what OSHA requires?","Yes. Wasatch evaluates the operation and applicable requirements, identifies gaps, and helps translate those findings into practical corrective actions."],
  ["How does medical surveillance support work?","Industrial hygiene findings are connected with RN-supported occupational health expertise to help employers identify surveillance needs and coordinate program elements. Clinical services and final medical determinations remain with the appropriate licensed provider."],
  ["Where do you provide services?","Wasatch is based in Utah and serves clients throughout the Western United States. Travel and multi-site projects can be discussed during the initial consultation."],
  ["What information should we provide for a quote?","A brief process description, facility location, number of employees or similar exposure groups, target hazards, prior reports or SDSs, desired timing, and the decision you need the work to support."],
];
export default function FAQPage(){return <main><section className="bg-slate-950 py-24 text-white"><div className="shell"><p className="eyebrow text-sky-300">FAQ</p><h1 className="page-title mt-5">Straight answers before the work begins.</h1></div></section><section className="shell max-w-4xl py-24"><div className="grid gap-4">{faqs.map(([q,a])=><details key={q} className="card group p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 text-lg font-extrabold text-slate-950">{q}<span className="text-2xl text-orange-700 group-open:rotate-45">+</span></summary><p className="mt-4 max-w-3xl leading-7 text-slate-600">{a}</p></details>)}</div><div className="mt-14 rounded-2xl bg-slate-100 p-8 text-center"><h2 className="text-2xl font-extrabold text-slate-950">Still deciding what you need?</h2><p className="mt-3 text-slate-600">A short conversation is often enough to define the appropriate scope.</p><Link href="/contact" className="button button-primary mt-6">Ask a Question</Link></div></section></main>}
